In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/union_all.csv')
df.head()

video_id categoryId_string              publishedAt  view_count   likes  \
0  9dKZeL2UbUM             Music  2024-12-06 11:00:06 UTC     1164446   80104   
1  Dw-HGGAgxAU             Music  2024-12-03 23:34:04 UTC      655669   47657   
2  I0jHbsidh1g             Music  2024-11-27 10:00:07 UTC     3931247  175534   
3  NynGk2fUbIA             Music  2024-12-10 12:00:23 UTC      177900   18976   
4  GhWIgc1Cgxg             Music  2024-11-28 17:00:14 UTC     1266129   49932   

   comment_count                                  thumbnail_link  \
0           2117  https://i.ytimg.com/vi/9dKZeL2UbUM/default.jpg   
1           4241  https://i.ytimg.com/vi/Dw-HGGAgxAU/default.jpg   
2           3745  https://i.ytimg.com/vi/I0jHbsidh1g/default.jpg   
3           2203  https://i.ytimg.com/vi/NynGk2fUbIA/default.jpg   
4           1947  https://i.ytimg.com/vi/GhWIgc1Cgxg/default.jpg   

   comments_disabled trending_date channelTitle  \
0              False    2024-12-12          Ado   
1              False    2024-12-12          DDG   
2              False    2024-12-12          Eve   
3              False    2024-12-12          JO1   
4              False    2024-12-12          SCH   

                                               title pays  
0                                     【Ado】Episode X   JP  
1  DDG - Handling Business “Freestyle” (Official ...   US  
2                        lazy cat  – Eve Music Video   JP  
3  JO1 | 'Love & Hate' - 2024 JO1 JAM感謝祭~SUMMER F...   JP  
4                                     SCH - La pluie   FR

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1824 entries, 0 to 1823
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   video_id           1824 non-null   object
 1   categoryId_string  1824 non-null   object
 2   publishedAt        1824 non-null   object
 3   view_count         1824 non-null   int64 
 4   likes              1824 non-null   int64 
 5   comment_count      1824 non-null   int64 
 6   thumbnail_link     1824 non-null   object
 7   comments_disabled  1824 non-null   bool  
 8   trending_date      1824 non-null   object
 9   channelTitle       1824 non-null   object
 10  title              1824 non-null   object
 11  pays               1824 non-null   object
dtypes: bool(1), int64(3), object(8)
memory usage: 158.7+ KB


In [ ]:
X = df[["likes", "comment_count"]]
y = df["view_count"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression().fit(X_train_scaled, y_train)

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

r2 = model.score(X_train_scaled, y_train)
from sklearn.metrics import mean_squared_error, mean_absolute_error

r2 = model.score(X_train_scaled, y_train)
train_pred_model = model.predict(X_train_scaled)

mse = mean_squared_error(y_true=y_train, y_pred=train_pred_model)
mae = mean_absolute_error(y_true=y_train, y_pred=train_pred_model)

print(f"{r2=}")
print(f"{mse=}")
print(f"{mae=}")


r2=0.8619168441839402
mse=13599138783612.436
mae=1178434.4747378326


In [ ]:
import numpy as np

new = np.array([[7757, 141]])

new_scaled = scaler.transform(new)

prediction_views = model.predict(new_scaled)

prediction_views

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([603693.32775038])

In [ ]:
#Calcul des gains estimés (the average made from ads is $1 per 1000 views)
pred_earning = prediction_views / 1000
pred_earning

array([603.69332775])

In [ ]:
f'{pred_earning[0]:.2f}$'

'603.69$'

In [ ]:
# C'est important que l'utilisateur mette les deux valeurs séparées par un vergule

data = input("Please give two")

input_numeric = [float(i) for i in data.split(",")]

new = np.array([input_numeric])

new_scaled = scaler.transform(new)

prediction = model.predict(new_scaled)

prediction

Please give two29292,234


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1070530.64167403])

In [ ]:
model.predict([[-1.63768542e-01, -2.07492331e-01]])

array([1140732.4919267])

In [ ]:
pred_model = model.predict(X_test_scaled)

In [ ]:
r2 = model.score(X_test_scaled, y_test)
mse = mean_squared_error(y_true=y_test, y_pred=pred_model)
mae = mean_absolute_error(y_true=y_test, y_pred=pred_model)

print(f"{r2=}")
print(f"{mse=}")
print(f"{mae=}")

r2=0.626547815333667
mse=8215288026539.419
mae=1062669.4268491261


In [ ]:
model_2 = LinearRegression()
model_2.fit(X_train_scaled, y_train)

LinearRegression()

In [ ]:
test_pred_model_2 = model_2.predict(X_test_scaled)
r2 = model_2.score(X_test_scaled, y_test)
mse = mean_squared_error(y_true=y_test, y_pred=test_pred_model_2)
mae = mean_absolute_error(y_true=y_test, y_pred=test_pred_model_2)

print(f"{r2=}")
print(f"{mse=}")
print(f"{mae=}")

r2=0.626547815333667
mse=8215288026539.419
mae=1062669.4268491261


In [ ]:
model_2.coef_

array([8984213.62022597,  321190.04066271])

In [ ]:
import plotly.express as px
fig = px.bar(x=X.columns, y=model_2.coef_)
fig.show()

In [ ]:
import plotly.express as px
fig = px.scatter(df, "likes", "comment_count")
fig.show()

In [ ]:
df